- name: Condition demo
  hosts: localhost
  connection: local
  tasks:
    - name: x is greater than 10
      when: x|int > 10
      ansible.builtin.debug:
        msg: "x is greater than 10 "

    - name: x is lesser than 10
      when: x|int < 10
      ansible.builtin.debug:
        msg: "x is lesser than 10 "

# In when conditions variable doesnt need flower brackets

# command line args:  ansible-playbook -i ../inv -become  -e ansible_user=ec2-user -e ansible_password=DevOps321 04-condition.yml --extra-vars "x=9"